# 加载 Bazel 内置的 http_archive 规则
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


# 1. 引入 rules_proto 依赖
http_archive(
    name = "rules_proto",
    sha256 = "dc3fb206a2cb3441b485eb1e423165b231235a1ea9b031b4433cf7bc1fa460dd",
    strip_prefix = "rules_proto-5.3.0-21.7",
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.7.tar.gz",
    ],
)

# 定义 Abseil 库
# http_archive(
#     name = "com_google_absl",
#     urls = [
#         "https://github.com/abseil/abseil-cpp/archive/refs/tags/20211102.0.tar.gz",
#     ],
#     sha256 = "dcf71b9cba8dc0ca9940c4b316a0c796be8fab42b070bb6b7cab62b48f0e66c4",
#     strip_prefix = "abseil-cpp-20211102.0",
# )
local_repository(
    name = "com_google_absl",
    path = "/home/tars/projects/tcp_learning/data_structure/third_party/abseil-cpp-20211102.0",
)

# 3. 初始化 rules_proto
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

# 可选：C++ 规则依赖
load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")
rules_cc_dependencies()